title: "TiRKiO"
timezone: Europe/Zurich
url: https://tirkio.com
baseurl: ""
permalink: "/:title/"
favicon: 'assets/images/favicon.ico'
paginate: 30
paginate_path: "/page:num/"
disqus: 'tirkio'
locale: de_CH
lang: de-CH
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-last-modified-at
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      lang: de
      locale: de_CH
      sitemap: true
      seo:
        type: "Article"
